#!/usr/bin/env python
#
# Sample dropblox_ai exectuable.
#

import json
import copy
import sys
import time
import Queue

class InvalidMoveError(ValueError):
  pass

# A class representing an (i, j) position on a board.
class Point(object):
  def __init__(self, i=0, j=0):
    self.i = i
    self.j = j

# A class representing a Block object.
class Block(object):
  def __eq__(self, other):
    return self.translation.i == other.translation.i and self.translation.j == other.translation.j
  def __hash__(self):
    return hash(str(self.translation.i) + ',' + str(self.translation.j))
  def __init__(self, center, offsets):
    # The block's center and offsets should not be mutated.
    self.center = Point(center['i'], center['j'])
    self.offsets = tuple(Point(offset['i'], offset['j']) for offset in offsets)
    # To move the block, we can change the Point "translation" or increment
    # the value "rotation".
    self.translation = Point()
    self.rotation = 0

  # A generator that returns a list of squares currently occupied by this
  # block. Takes translations and rotations into account.
  def squares(self):
    if self.rotation % 2:
      for offset in self.offsets:
        yield Point(
          self.center.i + self.translation.i + (2 - self.rotation)*offset.j,
          self.center.j + self.translation.j - (2 - self.rotation)*offset.i,
        )
    else:
      for offset in self.offsets:
        yield Point(
          self.center.i + self.translation.i + (1 - self.rotation)*offset.i,
          self.center.j + self.translation.j + (1 - self.rotation)*offset.j,
        )

  def left(self):
    self.translation.j -= 1

  def right(self):
    self.translation.j += 1

  def up(self):
    self.translation.i -= 1

  def down(self):
    self.translation.i += 1

  def rotate(self):
    self.rotation += 1

  def unrotate(self):
    self.rotation -= 1

  # The checked_* methods below perform an operation on the block
  # only if it's a legal move on the passed in board.  They
  # return True if the move succeeded.
  def checked_left(self, board):
    self.left()
    if board.check(self):
        return True
    self.right()
    return False

  def checked_right(self, board):
    self.right()
    if board.check(self):
        return True
    self.left()
    return False

  def checked_down(self, board):
    self.down()
    if board.check(self):
        return True
    self.up()
    return False

  def checked_up(self, board):
    self.up()
    if board.check(self):
        return True
    self.down()
    return False

  def checked_rotate(self, board):
    self.rotate()
    if board.check(self):
        return True
    self.unrotate()
    return False

  def do_command(self, command):
    assert(command in ('left', 'right', 'up', 'down', 'rotate')), \
        'Unexpected command %s' % (command,)
    getattr(self, command)()

  def do_commands(self, commands):
    for command in commands:
      self.do_command(command)

  def reset_position(self):
    (self.translation.i, self.translation.j) = (0, 0)
    self.rotation = 0

# A class representing a board state. Stores the current block and the
# preview list and handles commands.
class Board(object):
  rows = 33
  cols = 12

  def __init__(self, bitmap, block, preview):
    self.bitmap = bitmap
    self.block = block
    self.preview = preview

  def __repr__(self):
    return str(self)

  def __str__(self):
    return '\n'.join(' '.join('X' if elt else '.' for elt in row) for row in self.bitmap)

  @staticmethod
  def construct_from_json(state_json):
    state = json.loads(state_json)
    block = Block(state['block']['center'], state['block']['offsets'])
    preview = [Block(data['center'], data['offsets']) for data in state['preview']]
    return Board(state['bitmap'], block, preview)

  # Returns True if the block is in valid position - that is, if all of its squares
  # are in bounds and are currently unoccupied.
  def check(self, block):
    for square in block.squares():
      if (square.i < 0 or square.i >= self.rows or
          square.j < 0 or square.j >= self.cols or
          self.bitmap[square.i][square.j]):
        return False
    return True

  # Handles a list of commands to move the current block, and drops it at the end.
  # Appends a 'drop' command to the list if it does not appear, and returns the
  # new Board state object.
  #
  # If the block is ever in an invalid position during this method, throws an
  # InvalidMoveError.
  def do_commands(self, commands):
    self.block.reset_position()
    if not self.check(self.block):
      raise InvalidMoveError()
    commands.append('drop')
    for command in commands:
      if command == 'drop':
        new_board = self.place()
        return new_board
      else:
        self.block.do_command(command)
        if not self.check(self.block):
          raise InvalidMoveError()

  # Drops the current block as far as it can fall unobstructed, then locks it onto the
  # board. Returns a new board with the next block drawn from the preview list.
  #
  # Assumes the block starts out in valid position. This method mutates the current block
  #
  # If there are no blocks left in the preview list, this method will fail badly!
  # This is okay because we don't expect to look ahead that far.
  def place(self):
    while self.check(self.block):
      self.block.down()
    self.block.up()
    # Deep-copy the bitmap to avoid changing this board's state.
    new_bitmap = [list(row) for row in self.bitmap]
    for square in self.block.squares():
      new_bitmap[square.i][square.j] = 1
    new_bitmap = Board.remove_rows(new_bitmap)
    if len(self.preview) == 0:
      print "There are no blocks left in the preview list! You can't look that far ahead."
      return None
    return Board(new_bitmap, self.preview[0], self.preview[1:])

  def __hash__(self):
    return hash(str(self.draw_board()))

  def __eq__(self, other):
    return str(self.draw_board()) == str(other.draw_board()) 

  def draw_board(self):
    ret = [list(row) for row in self.bitmap]
    for offset in self.block.offsets:
      ret[self.block.center.i + offset.i][self.block.center.j + offset.j] = 1
    return ret

  # A helper method used to remove any full rows from a bitmap. Returns the new bitmap.
  @staticmethod
  def remove_rows(bitmap):
    (rows, cols) = (len(bitmap), len(bitmap[0]))
    new_bitmap = [row for row in bitmap if not all(row)]
    return [cols*[0] for i in range(rows - len(new_bitmap))] + new_bitmap

  # returns aggregate height of board
  def findAggregateHeight(self, bitmap):
    # can probably keep this as a class variable in the board
    output = 0

    for j in xrange(self.cols):
      highestRow = 35
      for i in reversed(xrange(self.rows)):
        if bitmap[i][j] > 0 and i < highestRow:
          highestRow = i
      output += highestRow

    return output

  # find number of lines that are completed
  def findCompleteLines(self, bitmap):
    output = 0
    for i in reversed(xrange(self.rows)):
      complete = True
      for j in xrange(self.cols):
        if bitmap[i][j] == 0:
          complete = False
          break
      if complete:
        output += 1
    return output

  # find the number of holes in the board
  def findHoles(self, bitmap):
    count = 0
    for i in reversed(xrange(1,33)):
      check = 0
      for j in xrange(12):
        if (bitmap[i][j] == 0):
          check = check + 1
          if (bitmap[i-1][j] != 0):
            count = count + 1
      if (check == 12):
        break
    return count

  # find the number of wells in the board
  def findWells(self, bitmap):
    heights = [0]*12
    for j in xrange(12):
      for i in xrange(33):
        if (bitmap[i][j] != 0):
          heights[j] = 32 - i
          break
    bumpiness = 0
    for i in xrange(len(heights) - 1):
      bumpiness += abs(heights[i] - heights[i+1])
    return bumpiness

def findBest(board, block):
  visited = set()
  q = Queue.Queue()
  q.put(([],copy.deepcopy(block)))
  solutions = []
  while not q.empty():
    ins,b = q.get()
    nb = copy.deepcopy(b)
    nb.left()
    if board.check(nb) and (nb not in visited):
      q.put((ins + ['left'],nb))
      visited.add(nb)
    nb = copy.deepcopy(b)
    nb.right()
    if board.check(nb) and (nb not in visited):
      q.put((ins+['right'],nb))
      visited.add(nb)
    nb = copy.deepcopy(b)
    nb.up()
    if board.check(nb) and (nb not in visited):
      q.put((ins+['up'],nb))
      visited.add(nb)
    nb = copy.deepcopy(b)
    nb.down()
    if board.check(nb) and (nb not in visited):
      q.put((ins+['down'],nb))
      visited.add(nb)
    if not board.check(nb):
      solutions.append((ins,b))

  boardScores = []

  for (instructions, block) in solutions:
    print >> sys.stderr, "== solution =="
    replaceBoard = copy.deepcopy(board)
    # move block to new position
    for currInstruction in instructions:
      print >> sys.stderr, currInstruction
      if currInstruction == "down":
        replaceBoard.block.down()
      elif currInstruction == "up":
        replaceBoard.block.up()
      elif currInstruction == "left":
        replaceBoard.block.left()
      elif currInstruction == "right":
        replaceBoard.block.right()
    
    # find score for this board
    score = 0
    score += replaceBoard.findCompleteLines(replaceBoard.bitmap) * 0.99275
    score += replaceBoard.findAggregateHeight(replaceBoard.bitmap) * -0.66569
    score += replaceBoard.findHoles(replaceBoard.bitmap) * -0.46544
    score += replaceBoard.findWells(replaceBoard.bitmap) * -0.24077
    boardScores.append(score)
  
  # find max score
  maxScore = 0
  index = 0
  for i in xrange(len(boardScores)):
    if boardScores[i] > maxScore:
      index = i
  return index, solutions[i][0]

if __name__ == '__main__':
  if len(sys.argv) == 3:
    # This AI executable will be called with two arguments: a JSON blob of the
    # game state and the number of seconds remaining in this game.
    seconds_left = float(sys.argv[2])

    # current board
    board = Board.construct_from_json(sys.argv[1])

    block = board.block

    rotated = [0]*4
    for i in xrange(4):
      b = copy.deepcopy(board)
      for j in xrange(i+1):
        b.block.rotate()
      blck = b.block
      rotated[i] = findBest(b, blck)

    maxScore = 0
    for i in xrange(4):
      if (maxScore < rotated[i][0]):
        maxScore = i

    instructionsToUse = rotated[i][1]

    for ins in instructionsToUse:
      print ins
    sys.stdout.flush()          # flush stdout


    # this will do the same thing, but with different helper methods
    #while block.checked_left(board):
      #print 'left'
    #sys.stdout.flush()
